### ISSUE TITLE
Create Payroll Tracker

### ISSUE THREAD

**Issue by jonghoBae0218** [jonghoBae0218/Payroll_tracker#1]
- [x] WHEN I click the "Add employee" button, I am presented with a series of prompts asking for first name, last name, and salary
- [x] WHEN I finish adding an employee, I am prompted to continue or cancel
- [x] WHEN I choose to continue, I am prompted to add a new employee
- [x] WHEN I choose to cancel, my employee data is displayed on the page sorted alphabetically by last name, and the console shows computed and aggregated data

**Comment by jonghoBae0218** [comment]
First commit fixed issue 1 and 2

**Comment by jonghoBae0218** [comment]
Second commit restructured files

**Comment by jonghoBae0218** [comment]
Third commit put files into original location(to not fix css file link to html file).
Also resolved issues 3 and 4

**Comment by jonghoBae0218** [comment]
Fourth commit has comments to js files and includes readme file
